import { format } from 'date-fns';
import {
  BarChart3,
  Compass,
  Copy,
  ExternalLink,
  FileText,
  HeartHandshake,
  MoreVertical,
  Package,
  Search,
  ShieldCheck,
  Smile,
} from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';

import type { AdminSurvey } from '@/types/admin.types';
import { TablePagination } from '@components/common/TablePagination';
import { Badge } from '@components/ui/badge';
import { Button } from '@components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@components/ui/card';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@components/ui/dropdown-menu';
import { Input } from '@components/ui/input';
import { useAdminSurveys } from '@features/admin/hooks';
import { useDebouncedValue } from '@hooks/useDebouncedValue';

import { AdminSurveyResponsesModal } from './AdminSurveyResponsesModal';

const PAGE_SIZE = 10;

function getSurveyTheme(title: string | null | undefined, description?: string | null) {
  const text = `${title ?? ''} ${description ?? ''}`.toLowerCase();

  if (
    text.includes('satisfaction') ||
    text.includes('csat') ||
    text.includes('nps') ||
    text.includes('happy') ||
    text.includes('feedback') ||
    text.includes('review')
  ) {
    return {
      icon: Smile,
      bg: 'bg-emerald-500/10',
      text: 'text-emerald-600 dark:text-emerald-400',
    };
  }
  if (
    text.includes('product') ||
    text.includes('feature') ||
    text.includes('preference') ||
    text.includes('pricing') ||
    text.includes('app')
  ) {
    return {
      icon: Package,
      bg: 'bg-blue-500/10',
      text: 'text-blue-600 dark:text-blue-400',
    };
  }
  if (
    text.includes('onboarding') ||
    text.includes('experience') ||
    text.includes('journey') ||
    text.includes('lead')
  ) {
    return {
      icon: Compass,
      bg: 'bg-purple-500/10',
      text: 'text-purple-600 dark:text-purple-400',
    };
  }
  if (
    text.includes('market') ||
    text.includes('validation') ||
    text.includes('research') ||
    text.includes('growth') ||
    text.includes('analytics')
  ) {
    return {
      icon: BarChart3,
      bg: 'bg-amber-500/10',
      text: 'text-amber-600 dark:text-amber-400',
    };
  }
  if (
    text.includes('security') ||
    text.includes('risk') ||
    text.includes('compliance') ||
    text.includes('audit')
  ) {
    return {
      icon: ShieldCheck,
      bg: 'bg-rose-500/10',
      text: 'text-rose-600 dark:text-rose-400',
    };
  }
  if (
    text.includes('customer') ||
    text.includes('user') ||
    text.includes('client') ||
    text.includes('partner')
  ) {
    return {
      icon: HeartHandshake,
      bg: 'bg-teal-500/10',
      text: 'text-teal-600 dark:text-teal-400',
    };
  }
  return {
    icon: FileText,
    bg: 'bg-orange-500/10',
    text: 'text-orange-600 dark:text-orange-400',
  };
}

interface AdminUserSurveysTableProps {
  userId: number;
  userName?: string;
}

export function AdminUserSurveysTable({ userId, userName }: AdminUserSurveysTableProps) {
  const [search, setSearch] = useState('');
  const [offset, setOffset] = useState(0);
  const [activeSurveyForResponses, setActiveSurveyForResponses] = useState<{
    id: number;
    title: string;
  } | null>(null);
  const debouncedSearch = useDebouncedValue(search, 300);

  const { data, isLoading, isError } = useAdminSurveys({
    user_id: userId,
    limit: PAGE_SIZE,
    offset,
    search: debouncedSearch.trim() || undefined,
  });

  const surveys = data?.surveys ?? [];
  const total = data?.pagination?.total ?? 0;
  const currentOffset = data?.pagination?.offset ?? offset;
  const limit = data?.pagination?.limit ?? PAGE_SIZE;

  const handleCopyLink = (link: string | null) => {
    if (!link) {
      toast.info('No public link generated for this survey yet.');
      return;
    }
    const fullUrl = link.startsWith('http') ? link : `${window.location.origin}${link}`;
    void navigator.clipboard.writeText(fullUrl);
    toast.success('Public survey link copied to clipboard.');
  };

  return (
    <>
      <Card className="border-border bg-card shadow-xs">
        <CardHeader className="flex flex-col gap-4 pb-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <CardTitle className="text-foreground text-lg font-bold">
              Surveys Created by {userName ?? 'User'}
            </CardTitle>
            <p className="text-muted-foreground mt-0.5 text-xs">
              Review surveys generated by this user and explore customer responses.
            </p>
          </div>

          <div className="relative w-full sm:w-80 md:w-96">
            <Search className="text-muted-foreground pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2" />
            <Input
              type="search"
              placeholder="Search surveys..."
              value={search}
              onChange={(e) => {
                setSearch(e.target.value);
                setOffset(0);
              }}
              className="h-9 rounded-xl pl-9 text-xs"
            />
          </div>
        </CardHeader>

        <CardContent className="p-0">
          {isLoading && (
            <div className="text-muted-foreground py-20 text-center text-xs font-medium">
              Loading surveys...
            </div>
          )}

          {isError && (
            <div className="text-destructive px-6 py-8 text-center text-sm font-medium">
              Failed to load surveys. Please try again.
            </div>
          )}

          {!isLoading && !isError && (
            <>
              <div className="overflow-x-auto">
                <table className="w-full min-w-[620px] border-collapse text-left text-sm sm:min-w-0">
                  <thead className="bg-muted/95 sticky top-0 z-10 border-b backdrop-blur-xs">
                    <tr className="text-muted-foreground text-xs font-semibold tracking-wider uppercase">
                      <th className="px-5 py-3.5 text-left sm:px-6">Survey</th>
                      <th className="px-5 py-3.5 text-center sm:px-6">Status</th>
                      <th className="px-5 py-3.5 text-center sm:px-6">Responses</th>
                      <th className="px-5 py-3.5 text-center sm:px-6">Created On</th>
                      <th className="px-5 py-3.5 text-center sm:px-6">Actions</th>
                    </tr>
                  </thead>
                  <tbody className="divide-border divide-y">
                    {surveys.length === 0 ? (
                      <tr>
                        <td colSpan={5} className="text-muted-foreground py-16 text-center text-xs">
                          No surveys found for this user.
                        </td>
                      </tr>
                    ) : (
                      surveys.map((survey: AdminSurvey) => {
                        const theme = getSurveyTheme(
                          survey.workspace_name,
                          survey.workspace_description,
                        );
                        const IconComponent = theme.icon;
                        const isActive = survey.status === 'Active';

                        return (
                          <tr key={survey.id} className="hover:bg-muted/30 transition-colors">
                            <td className="px-6 py-4 text-left">
                              <div className="flex items-start gap-3.5">
                                <div
                                  className={`flex size-10 shrink-0 items-center justify-center rounded-xl ${theme.bg} ${theme.text}`}
                                >
                                  <IconComponent className="size-5" />
                                </div>
                                <div className="min-w-0 space-y-0.5">
                                  <p className="text-foreground truncate text-sm font-bold">
                                    {survey.workspace_name
                                      ? survey.workspace_name
                                      : `Survey #${survey.id}`}
                                  </p>
                                  <p className="text-muted-foreground line-clamp-1 text-xs">
                                    {survey.workspace_description ??
                                      `${survey.question_count} questions configured`}
                                  </p>
                                </div>
                              </div>
                            </td>

                            <td className="px-6 py-4 text-center">
                              <div className="flex justify-center">
                                <Badge
                                  variant={isActive ? 'default' : 'secondary'}
                                  className={
                                    isActive
                                      ? 'border-emerald-500/20 bg-emerald-500/10 text-xs font-semibold text-emerald-600 hover:bg-emerald-500/20 dark:text-emerald-400'
                                      : 'border-purple-500/20 bg-purple-500/10 text-xs font-semibold text-purple-600 hover:bg-purple-500/20 dark:text-purple-400'
                                  }
                                >
                                  {survey.status}
                                </Badge>
                              </div>
                            </td>

                            <td className="px-6 py-4 text-center">
                              <span className="text-foreground text-sm font-semibold">
                                {survey.responses_count.toLocaleString()}
                              </span>
                            </td>

                            <td className="text-muted-foreground px-6 py-4 text-center text-xs whitespace-nowrap">
                              {survey.created_at
                                ? format(new Date(survey.created_at), 'MMMM d, yyyy')
                                : 'N/A'}
                            </td>

                            <td className="px-6 py-4 text-center">
                              <div className="flex items-center justify-center gap-2">
                                <Button
                                  variant="outline"
                                  size="sm"
                                  onClick={() =>
                                    setActiveSurveyForResponses({
                                      id: survey.id,
                                      title: survey.workspace_name ?? '',
                                    })
                                  }
                                  className="h-8 cursor-pointer border-orange-200 text-xs font-semibold text-orange-600 hover:bg-orange-50 hover:text-orange-700 dark:border-orange-900/50 dark:text-orange-400 dark:hover:bg-orange-950/50"
                                >
                                  View Responses
                                </Button>

                                <DropdownMenu>
                                  <DropdownMenuTrigger asChild>
                                    <Button
                                      variant="ghost"
                                      size="icon"
                                      className="text-muted-foreground size-8 cursor-pointer"
                                      aria-label="More options"
                                    >
                                      <MoreVertical className="size-4" />
                                    </Button>
                                  </DropdownMenuTrigger>
                                  <DropdownMenuContent align="end">
                                    <DropdownMenuItem
                                      onClick={() => handleCopyLink(survey.survey_link)}
                                      className="cursor-pointer gap-2 text-xs"
                                    >
                                      <Copy className="size-3.5" />
                                      Copy Public Link
                                    </DropdownMenuItem>
                                    {survey.survey_link && (
                                      <DropdownMenuItem
                                        onClick={() => {
                                          const link = survey.survey_link ?? '';
                                          const fullUrl = link.startsWith('http')
                                            ? link
                                            : `${window.location.origin}${link}`;
                                          window.open(fullUrl, '_blank', 'noopener,noreferrer');
                                        }}
                                        className="cursor-pointer gap-2 text-xs"
                                      >
                                        <ExternalLink className="size-3.5" />
                                        Open Survey Page
                                      </DropdownMenuItem>
                                    )}
                                  </DropdownMenuContent>
                                </DropdownMenu>
                              </div>
                            </td>
                          </tr>
                        );
                      })
                    )}
                  </tbody>
                </table>
              </div>

              {/* Numbered Pagination */}
              <TablePagination
                total={total}
                limit={limit}
                offset={currentOffset}
                onPageChange={setOffset}
                isLoading={isLoading}
                itemLabel="surveys"
              />
            </>
          )}
        </CardContent>
      </Card>

      {/* Survey Responses Modal */}
      {activeSurveyForResponses && (
        <AdminSurveyResponsesModal
          surveyId={activeSurveyForResponses.id}
          surveyTitle={activeSurveyForResponses.title}
          isOpen={Boolean(activeSurveyForResponses)}
          onClose={() => setActiveSurveyForResponses(null)}
        />
      )}
    </>
  );
}
