import type { WorkspaceMentorStateValue } from '../types';

export interface AgentStep {
  id: number;
  name: string;
  description: string;
  details: string[];
}

export const AGENT_STEPS: AgentStep[] = [
  {
    id: 1,
    name: 'Idea Validation',
    description: 'Validated Idea + Problem Statement + Validation Score',
    details: [
      'Problem identification',
      'Idea clarity',
      'Customer problem',
      'Target audience hypothesis',
      'Solution definition',
      'Value proposition',
      'Idea feasibility',
      'Initial competitor check',
      'Validation survey/interviews',
      'Go / Rethink / Pivot decision',
    ],
  },
  {
    id: 2,
    name: 'Market Research & Business Model',
    description: 'Market Intelligence + Business Model + Revenue Model',
    details: [
      'Detailed market research (Survey Intelligence)',
      'Target audience',
      'Customer personas',
      'Customer pain points',
      'Competitor analysis',
      'Market size/opportunity',
      'Demand',
      'Pricing research',
      'Revenue model',
      'Business model',
      'Sales channels',
      'Cost structure',
      'Unit economics',
      'Revenue potential',
    ],
  },
  {
    id: 3,
    name: 'Survey Intelligence',
    description: 'Creates market surveys & analyzes customer sentiment',
    details: [
      'Creates customer market validation surveys.',
      'Collects and analyzes customer responses.',
      'Interprets overall market sentiment.',
      'Identifies recurring customer pain points.',
      "Measures customers' willingness to pay.",
      "Determines whether customer feedback validates the founder's original business assumptions.",
    ],
  },
  {
    id: 4,
    name: 'Financial & Capital Planning',
    description: 'Capital Plan + Financial Plan + Runway + Break-even Target',
    details: [
      'Available capital',
      'Initial investment',
      'Working capital',
      'Founder expenses',
      'Product/service development cost',
      'Marketing budget',
      'Hiring budget',
      'Monthly burn',
      'Runway',
      'Revenue projections',
      'Break-even estimation',
      'Cash-flow planning',
      'Funding gap',
      'Bootstrapping vs external capital',
    ],
  },
  {
    id: 5,
    name: 'MVP & Execution Planning',
    description: 'POC/MVP Scope + Execution Roadmap',
    details: [
      'POC requirement',
      'MVP definition',
      'Must-have features',
      'Nice-to-have features',
      'Future features',
      'Product/service scope',
      'Development roadmap',
      'Technology requirements',
      'Resource requirements',
      'Timeline',
      'Milestones',
      'Sprint planning',
      'Cost optimisation',
      'Execution roadmap',
    ],
  },
  {
    id: 6,
    name: 'Business Setup & Build Execution',
    description: 'Team + Resources + Operations + Build Execution Plan',
    details: [
      'Technical team requirements',
      'Non-technical team requirements',
      'Hiring',
      'Freelancer/agency/co-founder decisions',
      'Job descriptions',
      'Roles and responsibilities',
      'Office/work-mode requirement',
      'Vendor selection',
      'Tools/software',
      'Operations setup',
      'Company registration timing',
      'Contracts',
      'Basic legal/compliance requirements',
      'Product/service development',
      'Execution monitoring',
    ],
  },
  {
    id: 7,
    name: 'Pre-Traction & GTM',
    description: 'Pre-Customer Base + Waitlist + Community + GTM Plan',
    details: [
      'Exact target customers',
      'Where customers are available',
      'Brand positioning',
      'Messaging',
      'Landing page',
      'Waitlist',
      'WhatsApp communities',
      'Social media presence',
      'Founder content',
      'Educational/problem-awareness content',
      'Lead collection',
      'Partnerships',
      'Early customer conversations',
      'Pre-sales',
      'Early-access registrations',
      'Launch audience preparation',
    ],
  },
  {
    id: 8,
    name: 'Testing, Pilot & Improvement',
    description: 'Tested & Improved Product + Launch Readiness Score',
    details: [
      'QA',
      'User acceptance testing',
      'Pilot launch',
      'Beta users',
      'Product/service quality testing',
      'Usability testing',
      'Early customer feedback',
      'Feature feedback',
      'Pricing feedback',
      'Customer satisfaction',
      'Bugs/issues',
      'Quality standards',
      'Improvements',
      'Launch-readiness decision',
    ],
  },
  {
    id: 9,
    name: 'Launch, Traction & Customer Validation',
    description: 'Customers + Revenue + Traction + Market Evidence',
    details: [
      'Commercial launch',
      'Customer acquisition',
      'Sales execution',
      'Marketing campaigns',
      'Lead conversion',
      'Onboarding',
      'Customer support',
      'Revenue tracking',
      'Customer feedback',
      'Reviews/testimonials',
      'Retention',
      'Referral',
      'CAC',
      'LTV',
      'Conversion rate',
      'Churn',
      'Product-market signals',
      'Continuous improvement',
    ],
  },
  {
    id: 10,
    name: 'Break-Even & Growth',
    description: 'Break-Even Plan + Profitable Growth Roadmap',
    details: [
      'Break-even monitoring',
      'Revenue optimisation',
      'Cost optimisation',
      'Profitability',
      'Retention improvement',
      'Repeat customers',
      'Upselling',
      'Cross-selling',
      'Marketing ROI',
      'Sales productivity',
      'Team productivity',
      'Automation',
      'Process optimisation',
      'Customer success',
      'Growth experiments',
    ],
  },
  {
    id: 11,
    name: 'Scale, Expansion & Strategic Future',
    description: 'Scale / Expansion / Funding / Exit Strategy',
    details: [
      'Scaling teams',
      'Leadership structure',
      'SOPs',
      'Automation',
      'Technology scaling',
      'New markets',
      'New cities/countries',
      'New customer segments',
      'New products/services',
      'Partnerships',
      'Franchising/licensing',
      'Fundraising',
      'Investor readiness',
      'M&A opportunities',
      'Equity decisions',
      'Strategic sale',
      'IPO readiness where applicable',
      'Founder exit',
      'Succession',
      'Continue/reinvent/exit decision',
    ],
  },
];

export function getStepFromWorkspaceState(state?: WorkspaceMentorStateValue): number {
  switch (state) {
    case 'GATHERING_INFO':
      return 1;
    case 'READY_TO_VALIDATE':
    case 'VALIDATING':
      return 2;
    case 'VALIDATED':
      return 3;
    default:
      return 1;
  }
}
